apiVersion: v1
kind: Service
metadata:
  name: {{ template "blackfire.fullname" . }}
  labels:
    app: {{ template "blackfire.name" . }}
    chart: {{ template "blackfire.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: agent
      protocol: TCP
      name: agent
  selector:
    app: {{ template "blackfire.name" . }}
    release: {{ .Release.Name }}
